//===- PandasPsss.td - Pandas dialect passes -------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PANDAS_PASS
#define PANDAS_PASS

include "mlir/Pass/PassBase.td"

#endif // PANDAS_PASS
